from colorama import Fore


TEXT_PREFIX = " "
COLORS_ENABLED = True
DEFAULT_TEXT_COLOR = None
PRIMARY_TEXT_COLOR = Fore.LIGHTBLUE_EX
SUCCESS_TEXT_COLOR = Fore.GREEN
INFO_TEXT_COLOR = Fore.CYAN
WARNING_TEXT_COLOR = Fore.YELLOW
DANGER_TEXT_COLOR = Fore.RED
